name: Build

on:
  push:
    branches:
      - main
    pull_request:
      - '**'

# Only the latest workflow run is allowed to run for each PR / branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      # Cache python dependencies using "requirements.txt" as the cache key
      - name: Cache Dependencies ğŸ“‚
        uses: actions/cache@v3
        with:
          path: ./.venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      # Install python dependencies only if cache was not hit
      - name: Install Dependencies ğŸ“¦
        run: python -m venv --system-site-packages ./.venv && . ./.venv/bin/activate && pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - name: Run Ruff Linter ğŸš¨
        run: . ./.venv/bin/activate && make lint
